version: '3.4'

services:
  traefik:
    image: traefik:1.7.5-alpine
    command: --api
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    configs:
        - source: traefik
          target: /etc/traefik/traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jinx.pro.key
      - jinx.pro.pem
      - registry-htpasswd
    networks:
      - default
    deploy:
      labels:
        - traefik.port=8080
        - traefik.frotend.rule=Host:traefik.jinx.pro

  registry:
    image: registry:2
    networks:
      - default
    volumes: 
      - /var/lib/registry:/var/lib/registry
    secrets:
      - registry-htpasswd
    deploy:
      labels:
        - traefik.port=5000 # default port exposed by the registry
        - traefik.frontend.rule=Host:registry.jinx.pro
        - traefik.frontend.auth.basic.usersFile=/run/secrets/registry-htpasswd
      placement:
        constraints: [node.role == manager]

  shepherd:
    depends_on: [registry]
    image: docker
    entrypoint: /usr/local/bin/shepherd
    configs:
        - source: shepherd
          target: /usr/local/bin/shepherd
          mode: 0544
    environment:
      SLEEP_TIME: 600
      WITH_REGISTRY_AUTH: "true"
      BLACKLIST_SERVICES: "jinx_shepherd jinx_registry jinx_traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    deploy:
      placement:
        constraints:
        - node.role == manager
    
  www:
    depends_on: [registry]
    image: registry.jinx.pro/www
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:jinx.pro, www.jinx.pro

networks:
  default:
    driver: overlay

configs:
  traefik:
    file: ./traefik.toml
  shepherd:
    file: ./shepherd

secrets:
  jinx.pro.pem:
    file: ./secrets/jinx.pro.pem
  jinx.pro.key:
    file: ./secrets/jinx.pro.key
  registry-htpasswd:
    file: ./secrets/registry-htpasswd